# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"hello_world": "00_funcs.ipynb",
         "OptionCuda": "01_main.ipynb"}

modules = ["library_notebook.py",
           "main_notebook.py"]

doc_url = "https://dustinvanstee.github.io/my_python_code/"

git_url = "https://github.com/dustinvanstee/my_python_code/tree/main/"

def custom_doc_links(name): return None
