# AUTOGENERATED! DO NOT EDIT! File to edit: 00_funcs.ipynb (unless otherwise specified).

__all__ = ['hello_world']

# Cell

# This function will be exported to library_notebook.py
def hello_world(val):
    print(f"you just ran a function in library_notebook.py.  You passed {val}")