# AUTOGENERATED! DO NOT EDIT! File to edit: 01_main.ipynb (unless otherwise specified).

__all__ = []

# Cell
# Setup in notebook flag.  Useful when you export code and have some situations where you dont want certain part of code run like visulaizations..
# Or in this example, when you run as python, the relative path changes for your library ..

import sys,os
try: from nbdev.imports import IN_NOTEBOOK
except: IN_NOTEBOOK=False

if IN_NOTEBOOK :
    print("In Notebooke mode")
    import my_python_code.library_notebook as funcs

else :
    print("Running in batch mode")
    import library_notebook as funcs


# Cell


# Cell
print(f"IN_NOTEBOOK = {IN_NOTEBOOK}")